# Generated by Django 3.2.2 on 2021-08-18 10:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0002_alter_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Лимит суммы, которую можно потратить')),
                ('duration', models.DurationField(choices=[(datetime.timedelta(days=1), 'day'), (datetime.timedelta(days=7), 'week'), (datetime.timedelta(days=30), 'month')], verbose_name='Срок действия')),
                ('condition', models.CharField(choices=[('m', 'больше'), ('l', 'меньше')], max_length=1, verbose_name='Критерий (больше, меньше)')),
                ('color', models.CharField(default='#FF0000', max_length=7, validators=[django.core.validators.RegexValidator('#[a-f\\d]{6}')], verbose_name='Цвет(hex)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expiry_date', models.DateTimeField(verbose_name='Дата окончания цели')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='money.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
            },
        ),
    ]
