# Generated by Django 3.2.2 on 2021-08-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='expiry_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания цели'),
        ),
    ]
